### ISSUE TITLE
build dist_render error，“error: identifier "__hmul2_rn" is undefined”

### ISSUE THREAD

**Issue by whuhangzhang** [InternLandMark/LandMark#29]
@Saaaaln 

Thanks for your great work, but I meet cuda compilation errors while compiling dist_render following the rende me tutorial

```
/opt/conda/lib/python3.8/site-packages/torch/include/c10/core/SymInt.h(84): warning: integer conversion resulted in a change of sign

/mnt/nas-data/suishou.zh/LandMark2/dist_render/kernel/cuda_kernel/include/pe/column_major/pe_column_major_half2half.h(60): error: identifier "__hmul_rn" is undefined

/mnt/nas-data/suishou.zh/LandMark2/dist_render/kernel/cuda_kernel/include/pe/column_major/pe_column_major_half2half.h(91): error: identifier "__hmul_rn" is undefined

/mnt/nas-data/suishou.zh/LandMark2/dist_render/kernel/cuda_kernel/include/pe/column_major/pe_column_major_half2half.h(157): warning: variable "encoded_input_feature_j" was declared but never referenced

/mnt/nas-data/suishou.zh/LandMark2/dist_render/kernel/cuda_kernel/include/pe/column_major/pe_column_major_half2half.h(274): error: identifier "__hmul2_rn" is undefined

/mnt/nas-data/suishou.zh/LandMark2/dist_render/kernel/cuda_kernel/include/pe/column_major/pe_column_major_half2half.h(304): error: identifier "__hmul2_rn" is undefined

4 errors detected in the compilation of "/mnt/nas-data/suishou.zh/LandMark2/dist_render/kernel/cuda_kernel/pe_concate_mlp/column_major/pe_column_major_half2half.cu".
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "/opt/conda/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
```

**Comment by whuhangzhang** [comment]
ref： https://github.com/microsoft/onnxruntime/issues/15840 
fix
