### ISSUE TITLE
使用了示例中的MatrixCity Dataset，为什么生成的视频连贯性很差，不如介绍中的视频那么流畅？

### ISSUE THREAD

**Issue by martin416** [InternLandMark/LandMark#48]
使用了示例中的MatrixCity Dataset，参数用的是confs/matrixcity/matrixcity_2block_multi.txt，默认只生成了6张照片，生成的视频只有几秒，跟README中的示例相比，相差甚远；修改N_vis参数为-1，全部图片163张都生成了，但是视频连贯性很差，几乎不能看，不知道是什么原因，怎么可以生成流畅的视频，谢谢。

**Comment by Crush1111** [comment]
请问你用的是哪个文件夹的位姿
![Uploading c0b9b31bf955c150aefbba730f36739.png…]()

**Comment by Crush1111** [comment]
是pose文件里面的还是train文件夹下的

**Comment by martin416** [comment]
直接下载百度网盘中，pose文件中的block_A

**Comment by martin416** [comment]
自己没有使用colmap来生成那2个json文件

**Comment by Crush1111** [comment]
好的谢谢你 但是我的重建效果很差 只能迭代2000轮 之后就报了这个错误 你知道是什么原因吗Traceback (most recent call last):
  File "/home/songjiali/LandMark-1/app/trainer.py", line 664, in <module>
    train(init_args)
  File "/home/songjiali/LandMark-1/app/trainer.py", line 546, in train
    train_model.updateAlphaMask(tuple(reso_mask), increase_alpha_thresh)
  File "/home/songjiali/anaconda3/envs/landmark1/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/songjiali/LandMark-1/app/models/gridnerf_sequential.py", line 378, in updateAlphaMask
    xyz_min = valid_xyz.amin(0)
IndexError: amin(): Expected reduction dim 0 to have non-zero size.

**Comment by Crush1111** [comment]
您这个视频是怎么生成的可以解答一下吗

**Comment by Crush1111** [comment]
请问您解决了您提出的问题吗？

**Comment by chenyaoswu** [comment]
你好 后来你这边测试解决了连贯性问题吗 ？目前我们测试下来也这样

**Comment by itisfree** [comment]
> 您这个视频是怎么生成的可以解答一下吗

您好，想问下
你生成视频了吗？
