### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by jgghjgj** [InternLandMark/LandMark#49]
Traceback (most recent call last):
  File "/home/tom/mp4/LandMark/app/trainer.py", line 664, in <module>
    train(init_args)
  File "/home/tom/mp4/LandMark/app/trainer.py", line 106, in train
    train_dataset, test_dataset = prep_dataset(enable_lpips, args)
  File "/home/tom/mp4/LandMark/app/tools/train_utils.py", line 155, in prep_dataset
    train_dataset = dataset(
  File "/home/tom/mp4/LandMark/app/tools/dataloader/city_dataset.py", line 30, in __init__
    self.read_meta()
  File "/home/tom/mp4/LandMark/app/tools/dataloader/city_dataset.py", line 36, in read_meta
    meta = load_json_drone_data(
  File "/home/tom/mp4/LandMark/app/tools/dataloader/ray_utils.py", line 157, in load_json_drone_data
    H, W = img0.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Crush1111** [comment]
数据集路径，参数文件都检查一下

**Comment by DongniZhu** [comment]
> 回溯（最近一次调用）：文件“/home/tom/mp4/LandMark/app/trainer.py”，第 664 行，在 train（init_args） 文件“/home/tom/mp4/LandMark/app/trainer.py”，第 106 行，在火车 train_dataset 中，test_dataset = prep_dataset（enable_lpips，args） 文件“/home/tom/mp4/LandMark/app/tools/train_utils.py”，第 155 行，在 prep_dataset train_dataset = dataset（文件“/home/tom/mp4/LandMark/app/tools/dataloader/city_dataset.py”，第 30 行，**init** self.read_meta（） 文件“/home/tom/mp4/LandMark/app/tools/dataloader/city_dataset.py”，第 36 行，read_meta meta = load_json_drone_data（ 文件“/home/tom/mp4/LandMark/app/tools/dataloader/ray_utils.py”，第 157 行，在 load_json_drone_data H，W = img0.shape[：2] 属性错误： “NoneType”对象没有属性“shape”

Hello, have you solved this problem? I am also reproducing it now, may I ask for your guidance?
你好，请问这个问题您解决了吗？目前也在复现，请教您给予下指导可以吗？

**Comment by repeaterI** [comment]
Hi, I encountered the same problem and solved it by modified the `load_json_drone_data` method:
`imgfolder = os.path.join(root_dir, "images")`
`fnames = [os.path.join(imgfolder, os.path.basename(frame["file_path"])) for frame in meta["frames"]]`

Actually, the problem is most likely caused by the wrong path. I suggest checking what the `root_path` and `imgfolder` is, and then modify it accordingly.
